@startuml

title: Standard Data Type for Block

actor a1
participant "block.grid.walk" as p2
note right of p2
  rename make
  instead of walk
end note
participant "model.layout.gridwalk" as p8
note right of p8
  send blocks:gmk
  rename svg.markup
end note
participant "model.grid.walk" as p9
note right of p9
  replace with
  newmodel.walk
end note
participant "newmodel.walk" as p4

a1 -> p2: cells:dict
a1 <- p2: block:gmk
a1 -> p8: cells:dict
a1 <- p8: svg
a1 -> p9: cells:array
a1 <- p9: blocks:gmk
a1 -> p4: block:gmk
a1 <- p4: blocks:gmk

' cells:dict block.grid.walk
' block1:gmk block.newmodel.walk
' cells:dict model.layout.gridwalk
' cells:arry model.grid.walk
' actor Todo as a2
' actor "Recurrink" as a3
' participant ".info" as p1
' participant ".flatten" as p3
' participant "linearsvg.make" as p5
' participant "linearsvg.writeMeanderConf" as p6
' participant ".update" as p7
' p3 -> p5: block:gmk
' p3 <- p5: svg
' note right of p5
'   should send a
'   block of blocks
' end note
' p3 -> p6: cells:dict
' p3 <- p6: yaml
' a3 -> p1: model:str
' a3 <- p1: block:txt
' a3 -> p7: modek:str
@enduml
