@startuml

class cell.Init.generate {
   top
   axis: NONE
   facing_c: FALSE
   facing: NONE
   stroke: NONE
}
class cell.Geometry.generateFacingAny {
   top: FALSE
}
class cell.Geometry.generateFacingCentre {
   top: FALSE
}
class cell.Geometry.generateOne {
   axis
   top
   facing: NONE
}
class cell.Geometry.candidates {
   facing
}
class cell.Palette.generateOne {
   colors
}
class cell.Strokes.generateOne {
   colors
}

class cell.Spiral.make {
   clen
   bounds
}
class cell.Spiral.offset {
   clen
   pos
   points
}
class cell.Spiral.splitLine {
   line
   hole
}
class cell.Spiral.prettyPrint {
   clen
   db
}
class cell.Spiral.matrix {
   LEN
}
class cell.Spiral.r1 {
   s
   n
   l
}
class cell.Spiral.c1 {
   s
   n
   l
}
class cell.Spiral.r2 {
   s
   n
   l
}
class cell.Spiral.c2 {
   s
   n
   l
}

class cell.Transform.dataV2 {
   celldata
}
class cell.Transform.dataV3 {
   celldata
}
class cell.Transform.txDbv3Yaml {
   cells
   penwidth_mm: DECIMAL(1)
}
class cell.Transform.txDbv3YamlOneCell {
   cell
   penwidth_mm
}

class cell.CellData.layers {
   rinkid
   celldata: DICT()
}
class cell.CellData.layersRead {
   rinkid
}
class cell.CellData.layersWrite {
   rinkid
   celldata: DICT()
}
class cell.CellData.cellWrite {
   rinkid
   label
   cell
}
class cell.CellData.layersUpdate {
   rinkid
   celldata
}
class cell.Strokes.generateOne {
   colors
}
class cell.Layer.background {
   cell
}
class cell.Layer.foreground {
   geom
}
class cell.Layer.dimension {
   x
   y
   clen
}
class cell.Layer.points {
   x
   y
   stroke_width
   clen
}

class cell.InputValidator.validate {
   label
   cell
}
class cell.InputValidator.geometry {
   label
   geom
}

class cell.Line.guidelines {
   facing
   clen
   bounds
}
class cell.Line.collectPoints {
   guidelines
   facing: NONE
}
class cell.Line.orderGrid {
   guideline
   facing: NONE
}
class cell.Line.makeStripes {
   points
}
class cell.Line.sliceByThird {
   facing
   points
}


cell.Transform <|-- cell.CellData
cell.Db2 <|-- cell.Transform

cell.InputValidator.validate -- recurrink.build
cell.CellData.layers  -- recurrink.commit
cell.CellData.dataV2  -- recurrink.commit
cell.CellData.layers  -- recurrink.clone
cell.CellData.txDbv3Yaml -- recurrink.clone
cell.CellData.txDbv3YamlOneCell -- cell.CellData.txDbv3Yaml

cell.shape -- cell.Layer.background
cell.shape -- cell.Layer.foreground
cell.InputValidator.geometry -- cell.InputValidator.validate
cell.shape *-- cell.InputValidator.geometry

cell.Palette.generateOne -- cell.Init.generate
cell.Strokes.generateOne -- cell.Init.generate
cell.Geometry.generateOne *-- cell.Init.generate

cell.Layer.foreground -- block.make
cell.Layer.background -- block.make
cell.Line -- cell.shape

cell.Spiral.make -- cell.shape.Rectangle.draw

@enduml
