@startuml
title Recurrink 2.0

(*) --> recurrink.py

partition Recurrink {
  recurrink.py --> list
  recurrink.py --> read
  recurrink.py --> init
  recurrink.py --> update
  recurrink.py --> commit
  recurrink.py --> delete
}
partition Inkex {
  update --> load
  load --> add_metadata
}
partition TmpFile {
  init --> tf.write
  commit -->[digest] digest
  commit --> tf.read
  load --> tf.read
}
partition Layout {
  load --> transform
  load --> [control] create
  load -->[svg] build
  load -->[group] render
  render -->[pos] get_cell_by_position
  render -->[pos] blocknum_to_uu
}
partition Draw {
  render -->[shape, pos, data] shape
  render -->[cell] backgrounds
  shape --> circle
  shape --> line
  shape --> square
  shape --> triangle
  shape --> diamond
  shape --> text
}
partition Blocks {
  get_cell_by_position --> b.read
  build --> cells
}
partition Views {
  init -->[model] v.generate
  init -->[digest] v.read
  read -->[digest] v.read
  commit --> v.create
  delete -->[digest] v.delete
  v.read -->[digest] v.celldata 
  v.create -->[digest] v.count   
}
partition Models {
  get_cell_by_position -->[model] m.read
  v.generate --> m.generate
  list --> stats
}
partition Cells {
  transform -->[cells] c.transform
  c.create -->[view] c.read
  v.generate -->[control] c.generate
}
partition Styles {
  c.create -->[items] s.create
  c.generate -->[control] s.generate
  c.transform -->[control] s.transform
  s.create -->[items] s.validate
  c.update -->[items] s.update
  s.generate --> s.read
  s.generate -->[sid] s.read
}
partition Geometry {
  c.create -->[items] g.create
  c.generate -->[control] g.generate
  c.transform -->[control] g.transform
  g.create -->[items] g.read
  g.generate -->[gid] g.read
  g.create --> g.validate
}
legend right
  |        | source | destination |
  | init   | DB    | TMP   |
  | update | TMP   | SVG   |
  | commit | TMP   | DB    |
  | info   | DB    | STDOUT|
  | delete | STDIN | DB    |
endlegend
recurrink.py --> (*)
@enduml
