@startuml
title: Layout

' inherit    <|.. 
' implement  <--

recurrink --> model.LinearSvg
recurrink --> model.Svg
recurrink --> model.Views
model.Views --> block.BlockData
model.Svg <|.. model.LinearSvg
model.Layout <|.. model.Svg
model.Db <|.. model.Model
model.Model <|.. model.Views

recurrink --> block.Grid
recurrink --> block.TmpFile
palette --> block.PaletteMaker
block.Flatten <|.. block.Grid
block.Compass <|..  block.BlockData
block.BlockData --> cell.CellData
block.Flatten --> cell.Geomink
block.Grid --> cell.Geomink

cell.Meander <|.. cell.Shapes
cell.Shapes <|.. cell.Geomink 
cell.Geometry <|.. cell.Palette
cell.Palette <|.. cell.Strokes
cell.Strokes <|.. cell.CellData


@enduml
