@startuml
class model.ModelData.model {
   name: NONE
   mid: 0
}
class model.ModelData.modelRead {}
class model.ModelData.modelWrite {
   name
}
class model.ModelData.blocks {
   mid
   blocks_v1: DICT()
}
class model.ModelData.blocksRead {
   mid
}
class model.ModelData.blocksWrite {
   mid
   blocks
}
class model.ModelData.compass {
   mid
   conf: NONE
}
class model.ModelData.compassWrite {
   mid
   conf
}
class model.ModelData.compassRead {
   mid
}
class model.ModelData.pens {
   ver: NONE
}
class model.ModelData.setBlocksize {
   mid
}
class model.ModelData.positionString {
   mid
}
class model.ModelData.stats {}
class model.Init.setInput {
   mnam: NONE
   pen: NONE
}
class model.Init.generate {
   model
   pen
}
class model.Compass.axis {}
class model.Compass.all {
   cell
}
class model.Compass.one {
   cell
}
class model.SvgPalette.render {
   fn
   palette
}
class model.SvgPalette.hexRgb {
   hexstr
}
class model.SvgPalette.tableRows {
   palette
}
class model.SvgPalette.htmlHeader {}
class model.SvgPalette.htmlFooter {}
class model.SvgModel.explode {
   block
}
class model.SvgModel.walk {
   block
   cellnum
   b0
   b1
   CLEN
   edge
}
class model.SvgModel.build {
   block
}
class model.SvgModel.setSvgHeader {}
class model.SvgModel.render {
   model
   line: FALSE
}
class model.SvgModel.write {
   svgfile
}
model.Db2 <|-- model.ModelData
model.ModelData <|-- model.Init

model.ModelData.model -- recurrink.commit
model.ModelData.pens -- recurrink.clone

model.ModelData.model -- recurrink.explode
model.ModelData.pens -- recurrink.explode
model.ModelData.blocks -- recurrink.explode

model.SvgModel.explode -- recurrink.explode
model.SvgModel.render -- recurrink.explode

model.Init.setInput -- recurrink.init
model.Init.generate -- recurrink.init
model.Compass -- model.Init.generate

model.ModelData.model -- recurrink.read
model.ModelData.setBlocksize -- recurrink.read


@enduml
