#!/bin/bash

# opt 1 model=M has no value RETURN model
# opt 2 model=M RETURN nothing for success or error
# opt 3 model=M RETURN digest 

workdir=/home/gavin/Pictures/artWork/recurrences
s=0

# use randmoness to automatically select a model for recurrink to process
get_random_model() {
  model_path=$(ls -1d ${workdir}/*| sort -R| tail -1)
  model=${model_path%.*}  # retain the part before the colon
  model=${model##*/}  # retain the part after the last slash
}

get_cells() {
  cells=$(./recurrink.py -m ${model} --output CSV --random)
  if [ -z "${cells}" ]
  then
    echo "cannot find cells for ${model}"
    exit 1
  fi
}

update_svg() {
  for cell in ${cells}
  do
    echo -n "$cell" 
    attrs=$(./recurrink.py -m ${model} --cell ${cell})
    a=($attrs)  # convert to array with the magic of IFS separator
    shape=${a[2]} # elems 0,1 are cell and model names
    size=${a[3]}
    facing=${a[4]}
    bgcol=${a[6]}
    width=${a[9]}
    top=${a[12]}
    # update cells
    # echo "c ${cell},m ${model},s ${shape},w ${width},f ${facing},z ${size},b ${bgcol},t ${top}"
    # 0 1        2      3      4    5    6               7   8    9 0 1   2
    # a soleares circle medium west #fff mediumvioletred 1.0 #000 0 0 1.0 True
    # d,soleares,circle,1.0,south,large,white,False
  ./effect.py \
     --id ${cell}1 \
     --output /tmp/${model}.svg \
     --shape ${shape} \
     --width ${width} \
     --facing ${facing} \
     --size ${size} \
     --bg ${bgcol} \
     --top ${top} /tmp/${model}.svg
  done
}
usage() { 
  echo "Usage: $0 [-n new model ] [ -s scale ] [-m <model> -d get digest ] [ -m <model> -r make rink ] " 1>&2; exit 1; 
}

while getopts "m:nsd:r:" o; do
  case "${o}" in
    d)
      d=${OPTARG}
      ;;
    r)
      r=${OPTARG}
      ;;
    m)
      m=${OPTARG}
      ;;
    n)
      get_random_model
      n=${model}
      ;;
    s)
      s=1
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${n}" ] && [ -z "${m}" ] && [ -z "${s}" ]; then
    usage
fi

if [ -n "${n}" ]; then
  echo ${n}
elif [ "${s}" -eq 1 ]; then
  # scaling is weighted in favour of 1:1
  declare -a a=(1.0 0.5 1.0 2.0 1.0)
  i=$((0 + $RANDOM % 5))
  echo ${a[$i]}
elif [ -n "${m}" ] && [ "${d}" == 'none' ]; then
  model=$m
  get_cells
  echo ${cells}
elif [ -n "${m}" ] && [ -n "${d}" ]; then
  model=$m
  if [ ! -f "/tmp/${model}.svg" ]
  then
    echo "File '$model.svg' not found in /tmp"
    exit 1
  else
    update_svg
    /bin/mv /tmp/${model}.svg ${d}.svg
    echo ${digest}
  fi
elif [ -n "${m}" ] && [ "${r}" == 'none' ]; then
  model=$m
  digest=$(./recurrink.py -m ${model} --output JSON --random)
  /bin/mv /tmp/${digest}.json ${workdir}/${model}/m
  echo $digest
  ./recurrink.py --view ${digest} --output RINK
  ./input.py --output ${digest}.svg /tmp/${model}.rink
elif [ -n "${m}" ] && [ -n "${r}" ]; then
  echo $r
  model=$m
  ./recurrink.py -m ${model} --output RINK --view $r
else
  usage
fi
