#!/usr/bin/env python

from model import Svg
from block import Make, Styles
from config import *

svg   = Svg()
block = Make()
block.walk(config.positions, config.cells)
if True:       # output to idraw
  block.meander(padding=False)
  svg.drawLine(block)
else: svg.draw(block)

'''
the
end
'''
