-- original direction has ('all', 'north', 'south', 'east', 'west')

ALTER TYPE direction ADD VALUE 'C' BEFORE 'all';
ALTER TYPE direction ADD VALUE 'N' AFTER 'north';
ALTER TYPE direction ADD VALUE 'E' AFTER 'east';
ALTER TYPE direction ADD VALUE 'S' AFTER 'south';
ALTER TYPE direction ADD VALUE 'W' AFTER 'west';
-- new
ALTER TYPE direction ADD VALUE 'NW';
ALTER TYPE direction ADD VALUE 'SW';
ALTER TYPE direction ADD VALUE 'SE';
ALTER TYPE direction ADD VALUE 'NE';

-- done
UPDATE geometry set facing='S' WHERE gid=1;
UPDATE geometry set facing='C' WHERE gid=2;
UPDATE geometry set facing='E' WHERE gid=3;
UPDATE geometry set facing='C' WHERE gid=4;
UPDATE geometry set facing='C' WHERE gid=5;
UPDATE geometry set facing='W' WHERE gid=6;
UPDATE geometry set facing='S' WHERE gid=7;
UPDATE geometry set facing='N' WHERE gid=8;
UPDATE geometry set facing='E' WHERE gid=9;
UPDATE geometry set facing='N' WHERE gid=10;
UPDATE geometry set facing='C' WHERE gid=11;
UPDATE geometry set facing='C' WHERE gid=12;
UPDATE geometry set facing='E' WHERE gid=13;
UPDATE geometry set facing='C' WHERE gid=14;
UPDATE geometry set facing='S' WHERE gid=15;
UPDATE geometry set facing='W' WHERE gid=16;
UPDATE geometry set facing='W' WHERE gid=17;
UPDATE geometry set facing='S' WHERE gid=18;
UPDATE geometry set facing='N' WHERE gid=19;
UPDATE geometry set facing='N' WHERE gid=20;
UPDATE geometry set facing='E' WHERE gid=21;
UPDATE geometry set facing='W' WHERE gid=22;
UPDATE geometry set facing='C' WHERE gid=23;
UPDATE geometry set facing='N' WHERE gid=24;
UPDATE geometry set facing='E' WHERE gid=25;
UPDATE geometry set facing='S' WHERE gid=26;
UPDATE geometry set facing='C' WHERE gid=27;
UPDATE geometry set facing='N' WHERE gid=28;
UPDATE geometry set facing='W' WHERE gid=29;
UPDATE geometry set facing='W' WHERE gid=30;
UPDATE geometry set facing='W' WHERE gid=31;
UPDATE geometry set facing='N' WHERE gid=32;
UPDATE geometry set facing='E' WHERE gid=33;
UPDATE geometry set facing='N' WHERE gid=34;
UPDATE geometry set facing='C' WHERE gid=35;
UPDATE geometry set facing='S' WHERE gid=36;
UPDATE geometry set facing='N' WHERE gid=37;
UPDATE geometry set facing='C' WHERE gid=41;
UPDATE geometry set facing='E' WHERE gid=42;
UPDATE geometry set facing='S' WHERE gid=43;
UPDATE geometry set facing='C' WHERE gid=44;
UPDATE geometry set facing='C' WHERE gid=45;
UPDATE geometry set facing='S' WHERE gid=46;
UPDATE geometry set facing='E' WHERE gid=47;
UPDATE geometry set facing='C' WHERE gid=48;
UPDATE geometry set facing='C' WHERE gid=49;
UPDATE geometry set facing='E' WHERE gid=50;
UPDATE geometry set facing='N' WHERE gid=53;
UPDATE geometry set facing='W' WHERE gid=54;
UPDATE geometry set facing='S' WHERE gid=55;
UPDATE geometry set facing='W' WHERE gid=56;
UPDATE geometry set facing='E' WHERE gid=57;
UPDATE geometry set facing='S' WHERE gid=60;
UPDATE geometry set facing='W' WHERE gid=70;
UPDATE geometry set facing='N' WHERE gid=71;
UPDATE geometry set facing='S' WHERE gid=72;
UPDATE geometry set facing='W' WHERE gid=73;
