-- funkytrunk
DELETE FROM compass WHERE model='funkytrunk';
DELETE FROM blocks WHERE model='funkytrunk';
DELETE FROM models WHERE model='funkytrunk';

INSERT INTO models (model, uniqcells, blocksizeXY, scale) 
VALUES ('funkytrunk', 13, '{12, 12}', 1.0);
-- a b a b a b a b a b a b
-- b c c e e c c e e c c a
-- a d d f f d d f f d d b
-- b g h k k k l l l h g a
-- a g h k k k l l l h g b
-- b i j k k k l l l j i a
-- a i j i j m m j i j i b
-- b g h g h m m h g h g a
-- a g h g h m m h g h g b
-- b i j i j m m j i j i a
-- a i j i j m m j i j i b
-- b m m m m m m m m m m a
INSERT INTO blocks (model, position, cell, top) 
VALUES 
  ('funkytrunk', '{  0,  0 }', 'a', null),
  ('funkytrunk', '{  1,  0 }', 'b', null),
  ('funkytrunk', '{  2,  0 }', 'a', null),
  ('funkytrunk', '{  3,  0 }', 'b', null),
  ('funkytrunk', '{  4,  0 }', 'a', null),
  ('funkytrunk', '{  5,  0 }', 'b', null),
  ('funkytrunk', '{  6,  0 }', 'a', null),
  ('funkytrunk', '{  7,  0 }', 'b', null),
  ('funkytrunk', '{  8,  0 }', 'a', null),
  ('funkytrunk', '{  9,  0 }', 'b', null),
  ('funkytrunk', '{ 10,  0 }', 'a', null),
  ('funkytrunk', '{ 11,  0 }', 'b', null),
  ('funkytrunk', '{  0,  1 }', 'b', null),
  ('funkytrunk', '{  1,  1 }', 'c', null),
  ('funkytrunk', '{  2,  1 }', 'c', null),
  ('funkytrunk', '{  3,  1 }', 'e', null),
  ('funkytrunk', '{  4,  1 }', 'e', null),
  ('funkytrunk', '{  5,  1 }', 'c', null),
  ('funkytrunk', '{  6,  1 }', 'c', null),
  ('funkytrunk', '{  7,  1 }', 'e', null),
  ('funkytrunk', '{  8,  1 }', 'e', null),
  ('funkytrunk', '{  9,  1 }', 'c', null),
  ('funkytrunk', '{ 10,  1 }', 'c', null),
  ('funkytrunk', '{ 11,  1 }', 'a', null),
  ('funkytrunk', '{  0,  2 }', 'a', null),
  ('funkytrunk', '{  1,  2 }', 'd', null),
  ('funkytrunk', '{  2,  2 }', 'd', null),
  ('funkytrunk', '{  3,  2 }', 'f', null),
  ('funkytrunk', '{  4,  2 }', 'f', null),
  ('funkytrunk', '{  5,  2 }', 'd', null),
  ('funkytrunk', '{  6,  2 }', 'd', null),
  ('funkytrunk', '{  7,  2 }', 'f', null),
  ('funkytrunk', '{  8,  2 }', 'f', null),
  ('funkytrunk', '{  9,  2 }', 'd', null),
  ('funkytrunk', '{ 10,  2 }', 'd', null),
  ('funkytrunk', '{ 11,  2 }', 'b', null),
  ('funkytrunk', '{  0,  3 }', 'b', null),
  ('funkytrunk', '{  1,  3 }', 'g', null),
  ('funkytrunk', '{  2,  3 }', 'h', null),
  ('funkytrunk', '{  3,  3 }', 'k', null),
  ('funkytrunk', '{  4,  3 }', 'k', null),
  ('funkytrunk', '{  5,  3 }', 'k', null),
  ('funkytrunk', '{  6,  3 }', 'l', null),
  ('funkytrunk', '{  7,  3 }', 'l', null),
  ('funkytrunk', '{  8,  3 }', 'l', null),
  ('funkytrunk', '{  9,  3 }', 'h', null),
  ('funkytrunk', '{ 10,  3 }', 'g', null),
  ('funkytrunk', '{ 11,  3 }', 'a', null),
  ('funkytrunk', '{  0,  4 }', 'a', null),
  ('funkytrunk', '{  1,  4 }', 'g', null),
  ('funkytrunk', '{  2,  4 }', 'h', null),
  ('funkytrunk', '{  3,  4 }', 'k', null),
  ('funkytrunk', '{  4,  4 }', 'k', null),
  ('funkytrunk', '{  5,  4 }', 'k', null),
  ('funkytrunk', '{  6,  4 }', 'l', null),
  ('funkytrunk', '{  7,  4 }', 'l', null),
  ('funkytrunk', '{  8,  4 }', 'l', null),
  ('funkytrunk', '{  9,  4 }', 'h', null),
  ('funkytrunk', '{ 10,  4 }', 'g', null),
  ('funkytrunk', '{ 11,  4 }', 'b', null),
  ('funkytrunk', '{  0,  5 }', 'b', null),
  ('funkytrunk', '{  1,  5 }', 'i', null),
  ('funkytrunk', '{  2,  5 }', 'j', null),
  ('funkytrunk', '{  3,  5 }', 'k', null),
  ('funkytrunk', '{  4,  5 }', 'k', null),
  ('funkytrunk', '{  5,  5 }', 'k', null),
  ('funkytrunk', '{  6,  5 }', 'l', null),
  ('funkytrunk', '{  7,  5 }', 'l', null),
  ('funkytrunk', '{  8,  5 }', 'l', null),
  ('funkytrunk', '{  9,  5 }', 'j', null),
  ('funkytrunk', '{ 10,  5 }', 'i', null),
  ('funkytrunk', '{ 11,  5 }', 'a', null),
  ('funkytrunk', '{  0,  6 }', 'a', null),
  ('funkytrunk', '{  1,  6 }', 'i', null),
  ('funkytrunk', '{  2,  6 }', 'j', null),
  ('funkytrunk', '{  3,  6 }', 'i', null),
  ('funkytrunk', '{  4,  6 }', 'j', null),
  ('funkytrunk', '{  5,  6 }', 'm', null),
  ('funkytrunk', '{  6,  6 }', 'm', null),
  ('funkytrunk', '{  7,  6 }', 'j', null),
  ('funkytrunk', '{  8,  6 }', 'i', null),
  ('funkytrunk', '{  9,  6 }', 'j', null),
  ('funkytrunk', '{ 10,  6 }', 'i', null),
  ('funkytrunk', '{ 11,  6 }', 'b', null),
  ('funkytrunk', '{  0,  7 }', 'b', null),
  ('funkytrunk', '{  1,  7 }', 'g', null),
  ('funkytrunk', '{  2,  7 }', 'h', null),
  ('funkytrunk', '{  3,  7 }', 'g', null),
  ('funkytrunk', '{  4,  7 }', 'h', null),
  ('funkytrunk', '{  5,  7 }', 'm', null),
  ('funkytrunk', '{  6,  7 }', 'm', null),
  ('funkytrunk', '{  7,  7 }', 'h', null),
  ('funkytrunk', '{  8,  7 }', 'g', null),
  ('funkytrunk', '{  9,  7 }', 'h', null),
  ('funkytrunk', '{ 10,  7 }', 'g', null),
  ('funkytrunk', '{ 11,  7 }', 'a', null),
  ('funkytrunk', '{  0,  8 }', 'a', null),
  ('funkytrunk', '{  1,  8 }', 'g', null),
  ('funkytrunk', '{  2,  8 }', 'h', null),
  ('funkytrunk', '{  3,  8 }', 'g', null),
  ('funkytrunk', '{  4,  8 }', 'h', null),
  ('funkytrunk', '{  5,  8 }', 'm', null),
  ('funkytrunk', '{  6,  8 }', 'm', null),
  ('funkytrunk', '{  7,  8 }', 'h', null),
  ('funkytrunk', '{  8,  8 }', 'g', null),
  ('funkytrunk', '{  9,  8 }', 'h', null),
  ('funkytrunk', '{ 10,  8 }', 'g', null),
  ('funkytrunk', '{ 11,  8 }', 'b', null),
  ('funkytrunk', '{  0,  9 }', 'b', null),
  ('funkytrunk', '{  1,  9 }', 'i', null),
  ('funkytrunk', '{  2,  9 }', 'j', null),
  ('funkytrunk', '{  3,  9 }', 'i', null),
  ('funkytrunk', '{  4,  9 }', 'j', null),
  ('funkytrunk', '{  5,  9 }', 'm', null),
  ('funkytrunk', '{  6,  9 }', 'm', null),
  ('funkytrunk', '{  7,  9 }', 'j', null),
  ('funkytrunk', '{  8,  9 }', 'i', null),
  ('funkytrunk', '{  9,  9 }', 'j', null),
  ('funkytrunk', '{ 10,  9 }', 'i', null),
  ('funkytrunk', '{ 11,  9 }', 'a', null),
  ('funkytrunk', '{  0, 10 }', 'a', null),
  ('funkytrunk', '{  1, 10 }', 'i', null),
  ('funkytrunk', '{  2, 10 }', 'j', null),
  ('funkytrunk', '{  3, 10 }', 'i', null),
  ('funkytrunk', '{  4, 10 }', 'j', null),
  ('funkytrunk', '{  5, 10 }', 'm', null),
  ('funkytrunk', '{  6, 10 }', 'm', null),
  ('funkytrunk', '{  7, 10 }', 'j', null),
  ('funkytrunk', '{  8, 10 }', 'i', null),
  ('funkytrunk', '{  9, 10 }', 'j', null),
  ('funkytrunk', '{ 10, 10 }', 'i', null),
  ('funkytrunk', '{ 11, 10 }', 'b', null),
  ('funkytrunk', '{  0, 11 }', 'b', null),
  ('funkytrunk', '{  1, 11 }', 'm', null),
  ('funkytrunk', '{  2, 11 }', 'm', null),
  ('funkytrunk', '{  3, 11 }', 'm', null),
  ('funkytrunk', '{  4, 11 }', 'm', null),
  ('funkytrunk', '{  5, 11 }', 'm', null),
  ('funkytrunk', '{  6, 11 }', 'm', null),
  ('funkytrunk', '{  7, 11 }', 'm', null),
  ('funkytrunk', '{  8, 11 }', 'm', null),
  ('funkytrunk', '{  9, 11 }', 'm', null),
  ('funkytrunk', '{ 10, 11 }', 'm', null),
  ('funkytrunk', '{ 11, 11 }', 'a', null);
--   all: a b m
-- north: g h i j k l
--  east: c d e f
INSERT INTO compass (model, cell, pair, facing)
VALUES
  ('funkytrunk', 'a', null, 'all'),
  ('funkytrunk', 'b', null, 'all'),
  ('funkytrunk', 'm', null, 'all'),
  ('funkytrunk', 'c', 'd', 'east'),
  ('funkytrunk', 'e', 'f', 'east'),
  ('funkytrunk', 'g', 'h', 'north'),
  ('funkytrunk', 'i', 'j', 'north'),
  ('funkytrunk', 'k', 'l', 'north');
