-- INSERT INTO models (model, uniqcells, blocksizeXY, scale) 
-- VALUES ('testcard', 15, '{10, 4}', 1.0);

INSERT INTO blocks (model, position, cell) 
VALUES 
('testcard', '{0, 0}', 'x'), 
('testcard', '{0, 1}', 'x'), 
('testcard', '{0, 2}', 'x'), 
('testcard', '{0, 3}', 'x'), 
('testcard', '{2, 0}', 'x'), 
('testcard', '{2, 1}', 'x'), 
('testcard', '{2, 2}', 'x'), 
('testcard', '{2, 3}', 'x'), 
('testcard', '{4, 0}', 'x'), 
('testcard', '{5, 0}', 'x'), 
('testcard', '{6, 0}', 'x'), 
('testcard', '{7, 0}', 'x'), 
('testcard', '{4, 1}', 'x'), 
('testcard', '{5, 1}', 'x'), 
('testcard', '{6, 1}', 'x'), 
('testcard', '{7, 1}', 'x'), 
('testcard', '{4, 2}', 'x'), 
('testcard', '{6, 2}', 'x'), 
('testcard', '{4, 3}', 'x'), 
('testcard', '{6, 3}', 'x'), 
('testcard', '{8, 0}', 'x'), 
('testcard', '{9, 0}', 'x'), 
('testcard', '{8, 1}', 'x'), 
('testcard', '{9, 1}', 'x'), 
('testcard', '{8, 2}', 'x'), 
('testcard', '{8, 3}', 'x'), 
('testcard', '{1, 1}', 'A'), 
('testcard', '{3, 1}', 'B'), 
('testcard', '{1, 3}', 'C'), 
('testcard', '{3, 3}', 'D'), 
('testcard', '{5, 3}', 'E'), 
('testcard', '{7, 3}', 'F'), 
('testcard', '{9, 3}', 'G'), 
('testcard', '{1, 0}', 'a'), 
('testcard', '{3, 0}', 'b'), 
('testcard', '{1, 2}', 'c'), 
('testcard', '{3, 2}', 'd'), 
('testcard', '{5, 2}', 'e'), 
('testcard', '{7, 2}', 'f'), 
('testcard', '{9, 2}', 'g');
